openapi: 3.0.3
info:
  title: I_TiMessengerContactManagement
  description: REST interface to manage the capabilities of contacts.
  version: 0.1.0
  # initiale Version
  contact:
    name: gematik GmbH
    email: software-development@gematik.de
    url: "https://www.gematik.de"
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0"

externalDocs:
  description: TI-Messenger-API
  url: https://github.com/gematik/api-ti-messenger

servers:
  - url: https://localhost/tim-contact-mgmt/
tags:
  - name: info
    description: This operation returns meta data about this interface and the status of available resources
  - name: contacts
    description: Operations for contact management

paths:
  /:
    get:
      tags:
        - info
      description: Returns the meta data of this interface.
      operationId: getInfo
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoObject"
        "403":
          $ref: "#/components/responses/Forbidden"
        default:
          $ref: "#/components/responses/DefaultResponse"

  /contacts:
    get:
      tags:
        - getContacts
      description: "Returns the contacts with invite settings."
      operationId: getContacts
      responses:
        200:
          description: "List of all contact settings of the user"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contacts"
        default:
          $ref: "#/components/responses/DefaultResponse"

  /contacts/{mxidUrl}:
    parameters:
      - $ref: "#/components/parameters/mxidUrl"

    get:
      tags:
        - getContact
      description: "Returns the contacts with invite settings."
      operationId: getContact
      responses:
        200:
          description: "Retrieve the setting for the contact {mxidUrl}."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        default:
          $ref: "#/components/responses/DefaultResponse"

    post:
      tags:
        - createContactSetting
      description: "Creates the setting for the contact {mxidUrl}."
      operationId: createContactSetting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: "Contact setting for {mxidUrl} successfully created"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/DefaultResponse"

    put:
      tags:
        - updateContactSetting
      description: "Updates the setting for the contact {mxidUrl}."
      operationId: updateContactSetting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "200":
          description: "Contact setting for {mxidUrl} successfully updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/DefaultResponse"

    delete:
      tags:
        - deleteContactSetting
      description: "Deletes the setting for the contact {mxidUrl}."
      operationId: deleteContactSetting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "204":
          description: Deleted
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          description: Unauthorized
        "404":
          $ref: "#/components/responses/NotFound"
        default:
          $ref: "#/components/responses/DefaultResponse"

# Descriptions of common components
components:

  parameters:

    mxidUrl:
      name: mxidUrl
      in: path
      description: "ID of the contact in url form."
      required: true
      schema:
        type: string
        example: "matrix:u/you:example.org"

  responses:
    DefaultResponse:
      description: "The default error response"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    NotFound:
      description: "The specified resource was not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    Unauthorized:
      description: "Unauthorized"
    Forbidden:
      description: "Forbidden - you are not allowed to do this"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    BadRequest:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:

    InfoObject:
      description: ""
      required:
        - title
        - version
      readOnly: true
      type: object
      properties:
        title:
          type: string
          description: "Der Titel der Anwendung"
          example: "Contact Management des TI-Messengers"
        description:
          type: string
          description: "Short description of the application"
          example: "Contact Management des TI-Messengers. Betreiber: <Betreibername>"
        contact:
          type: string
          description: "Contact information"
        version:
          type: string
          description: "Version der implementierten TiMessengerContactManagement Schnittstelle (Version der TiMessengerContactManagement.yaml Datei)"
          example: "1.0.0"

    Contact:
      readOnly: true
      description: "Contact settings."
      type: object
      properties:
        mxidUrl:
          type: string
          description: "ID of the contact in url form."
          example: "matrix:u/you:example.org"
        inviteSettings:
          type: object
          properties:
            start:
              type: string
              format: date-time
              description: Start date
              example: "2022-07-21T17:32:28+02:00"
            end:
              type: string
              format: date-time
              description: Start date
              example: "2022-08-21T17:32:28+02:00"
          description: "Invites from the mxidUrl are granted between start and end date-time."

    Error:
      description: "Default error object with information about the occurred error"
      type: object
      properties:
        errorCode:
          description: "a code identifying this error"
          type: string
        errorMessage:
          description: "a readable message describing the error"
          type: string
      required:
        - errorCode
        - errorMessage

    Contacts:
      description: "The list of contacts and their settings."
      type: object
      properties:
        contacts:
          description: "The list of contacts and their settings."
          type: array
          items:
            $ref: "#/components/schemas/Contact"
          readOnly: true


    mxidUrl:
      description: "Identifier of the device"
      type: object
      properties:
        mxidUrl:
          type: integer
          format: int64
          example: 4711
          description: "Identifier of a device"
